import time 
Product_Info=[1001,"Mobile_1",29000,"Samsung"]
print(Product_Info)
print()
print('====Product_Information====')
print("Pid is:",Product_Info[0])
print("Pname is:",Product_Info[1])
print("Price is:",Product_Info[2])
print("Company is:",Product_Info[3])
print()
print("=====Using slice operator=====")
print(Product_Info[0:])
print()
print(Product_Info[::-2])
print()
print(Product_Info[::2])
print()
time.sleep(2)
print('End of an application')