languange=input("enter the language:")
Day=int(input("enter the Day:"))
Month=int(input("enter the month:"))
Year=int(input("enter the year:"))
print("name of language:",languange)
print("date of release is:{}/{}/{}".format(Day,Month,Year))
