import time
D2=dict(D2=dict(pid=1001,Pname="mobile_1",price=2700,company="samsung"))
print(D2)
print()
print(type(D2))
print()
print("==keys and values")
print(D2.items())
print()
time.sleep(2)
print("end of code")