import time
D2=dict(Pid=1001,Pname="mobile_1",Price=27100,Company="samsung")
print(D2)
print()
print(type(D2))
print()
print("===keys()===")
D3=D2.clear()
print(D3)
print()
time.sleep(2)
print("end of code")
